name = vl_teleport_stations
title = Teleport Stations for VoxeLibre
description = Adds craftable teleport stations for VoxeLibre.
depends = mcl_core, mcl_compass
optional_depends = 
min_minetest_version = 5.13.0
author = xyzshantaram